name: Deploy Landscape Build to Branch

on:
  workflow_dispatch: # Manually trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Landscape2 and Build Site
        env:
          GITHUB_TOKEN: ${{ secrets.GH_FETCH_TOKEN }}
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/cncf/landscape2/releases/download/v1.0.0/landscape2-installer.sh | sh
          source $HOME/.cargo/env
          landscape2 build \
            --data-file data.yml \
            --settings-file settings.yml \
            --guide-file guide.yml \
            --logos-path logos \
            --output-dir build

      - name: Push Build to `build` Branch
        run: |
          cd build
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b build
          git add .
          git commit -m "Deploy from $GITHUB_SHA"
          git push --force origin build
